### ISSUE TITLE
PL_VERSION error

### ISSUE THREAD

**Issue by eldoradoli** [crockwell/far#1]
hello, when i try to run indoor demo, the system gives this error, how to solve it, good luck to you
``` python
2024-03-08 16:35:48.560 | INFO     | src.lightning.lightning_loftr:__init__:76 - Load 'pretrained_models/far_8pt.ckpt' as pretrained checkpoint
Traceback (most recent call last):
  File "/home/lt/githubProjects/far/mp3d_loftr/demo.py", line 144, in <module>
    model = PL_LoFTR(config, pretrained_ckpt=args.ckpt_path, split="test").eval().cuda()
  File "/home/lt/githubProjects/far/mp3d_loftr/src/lightning/lightning_loftr.py", line 80, in __init__
    self.pl_version = config.PL_VERSION
  File "/home/lt/anaconda3/envs/far/lib/python3.9/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: PL_VERSION
```

**Comment by crockwell** [comment]
Hi! 

Sorry to hear this error. Can you share which anaconda environment you installed and confirm you have pretrained_models/far_8pt.ckpt downloaded?

**Comment by eldoradoli** [comment]
yeah,i checked that i have downloaded far_8pt.ckpt and unzip it, and my environment is torch 2.0.1, i dont know what is and where to set pl_version

**Comment by crockwell** [comment]
Hey - thanks for point this out. My mistake -- I made a small change of including this for better compatibility of the train / test but didn't update the demo correspondingly. 

Should be fixed now, please let me know if it still doesn't work!

**Comment by eldoradoli** [comment]
thank you, it works now!
